version: '3.7'

services:
  web:
    volumes:
      - static:/app/static
      - media:/app/media
    env_file:
      - ./backend/.env
    build:
      context: ./backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://postgres:admin@db:5432/e_commerce
    depends_on:
      - db
  nginx:
    build: ./nginx
    volumes:
      - static:/app/static
      - media:/app/media
      - dist:/usr/share/nginx/html
    ports:
      - "80:80"
    depends_on:
      - web
      - frontend
  frontend:
    build:
      context: ./frontend
    volumes:
      - dist:/app/dist

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: e_commerce
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"  # Expose the database port to the host (optional, for development)
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  dist:
  static:
  media:

