# Generated by Django 5.0.7 on 2025-01-28 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='example',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
